### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by JerzyR** [ErikEJ/SqlCeBulkCopy#11]
What is supported NET Framework, I have installed on 4.7.1 in a project and all files presents but I'm getting error
Method not found: 'Void ErikEJ.SqlCe.SqlCeBulkCopy..ctor(System.Data.SqlServerCe.SqlCeConnection)'.

**Comment by ErikEJ** [comment]
Hmmm.. I currently target .NET 3.5, I will try to update to 4.0 - are you using the NuGet package, or source?

**Comment by ErikEJ** [comment]
I have updated the master branch - please let me know if you need a Nuget package update

**Comment by JerzyR** [comment]
Hi Erik

Thank you for your update, I’m good now

 

Jerzy

**Comment by ErikEJ** [comment]
Are you using the updated source?

**Comment by JerzyR** [comment]
Yes, downloaded the master source and targeting 4.7.1 , all works fine
