### ISSUE TITLE
Error InvalidCastException in ErikEJ.SqlCe.NetCF

### ISSUE THREAD

**Issue by dsuryanto** [ErikEJ/SqlCeBulkCopy#12]
Good Night Mr Eric.
Im David From Indonesia.
I want to ask something about Error in Your Library DLL.

I want to Insert Mass Data from SQL Server to SQL CE 3.5 which is used in Windows CE Handheld.

I Use your Library, but I got error Invalid Cast Exception.

 

Here My Code

//private static void DoBulkCopy(DataTable reader)

        //{

        //    string strTest = NaviComputer.Global.pubDatabase1;

        //    var connectionString = new SqlCeConnection("Data Source=" + strTest + "; Password = G3n3sysD4t4b4s3");

 

        //    using (SqlCeBulkCopy bc = new SqlCeBulkCopy(connectionString))

        //    {

        //        bc.ColumnMappings.Add("InternalID", "InternalID");

        //        bc.ColumnMappings.Add("Batch", "Batch");

        //        bc.ColumnMappings.Add("[File]", "File");

        //        bc.ColumnMappings.Add("Type", "Type");

        //        bc.ColumnMappings.Add("Status", "Status");

        //        bc.DestinationTableName = "t_prn";

        //        bc.WriteToServer(reader);

        //    }

        //}

Error when execute WriteToServer

Can you help me to solve that.

Thx Before.

**Comment by dsuryanto** [comment]
i already switch my code into this :

void insertprn()
        {
            if (status == true)
            {
                NaviComputer.Global.conn1 = new conn();
                StrQuery = "delete from t_prn";
                dell = NaviComputer.Global.conn1.executeQuery(StrQuery);

                var SaranaInsert = JsonConvert.DeserializeObject<List<Getprn>>(responsefromserver);

                var dt = new DataTable("Tabel_PRN");
                dt.Columns.Add("InternalID", typeof(string));
                dt.Columns.Add("Batch", typeof(string));
                dt.Columns.Add("File", typeof(string));
                dt.Columns.Add("type", typeof(string));
                dt.Columns.Add("Status", typeof(string));

                for (int i = 0; i < SaranaInsert.Count; i++)
                {
                    string InternalID = SaranaInsert[i].InternalID;
                    string Batch = SaranaInsert[i].Batch;
                    string File = SaranaInsert[i].File;
                    string Type = SaranaInsert[i].Type;
                    //string Status = SaranaInsert[i].Status;
                    string Status = "0";

                    dt.Rows.Add(new Object[] { InternalID, Batch, File, Type, Status });
                    //StrQuery = "insert into t_prn(InternalID,Batch,[File],Type,Status)values('" + InternalID + "','" + Batch + "','" + File + "','" + Type + "','" + Status + "')";
                    //insertt = NaviComputer.Global.conn1.executeQuery(StrQuery);
                }

                if (dt.Rows.Count > 0)
                {
                    string strTest = NaviComputer.Global.pubDatabase1;
                    string dataSource;
                    dataSource = "Data Source=" + strTest + "; Password = G3n3sysD4t4b4s3";
                    using (SqlCeBulkCopy bc = new SqlCeBulkCopy(dataSource))
                    {
                        bc.DestinationTableName = "t_prn";
                        bc.WriteToServer(dt);
                    }
                }

            }
        }

but still get error but get another error
the error is "System.Data.SqlServerCe.SqlCeException was unhandled"

**Comment by ErikEJ** [comment]
Add error handling, and look at the SqlCeException

**Comment by dsuryanto** [comment]
void insertprn()
        {
            if (status == true)
            {
                NaviComputer.Global.conn1 = new conn();
                StrQuery = "delete from t_prn";
                dell = NaviComputer.Global.conn1.executeQuery(StrQuery);

                var SaranaInsert = JsonConvert.DeserializeObject<List<Getprn>>(responsefromserver);

                var dt = new DataTable("Tabel_PRN");
                dt.Columns.Add("InternalID", typeof(string));
                dt.Columns.Add("Batch", typeof(string));
                dt.Columns.Add("File", typeof(string));
                dt.Columns.Add("type", typeof(string));
                dt.Columns.Add("Status", typeof(string));

                for (int i = 0; i < SaranaInsert.Count; i++)
                {
                    string InternalID = SaranaInsert[i].InternalID;
                    string Batch = SaranaInsert[i].Batch;
                    string File = SaranaInsert[i].File;
                    string Type = SaranaInsert[i].Type;
                    //string Status = SaranaInsert[i].Status;
                    string Status = "0";

                    dt.Rows.Add(new Object[] { InternalID, Batch, File, Type, Status });
                    //StrQuery = "insert into t_prn(InternalID,Batch,[File],Type,Status)values('" + InternalID + "','" + Batch + "','" + File + "','" + Type + "','" + Status + "')";
                    //insertt = NaviComputer.Global.conn1.executeQuery(StrQuery);
                }

                if (dt.Rows.Count > 0)
                {
                    string strTest = NaviComputer.Global.pubDatabase1;
                    con = new SqlCeConnection("Data Source=" + strTest + "; Password = G3n3sysD4t4b4s3");
                    con.Open();
                    using (SqlCeBulkCopy bc = new SqlCeBulkCopy(con))
                    {
                        bc.DestinationTableName = "t_prn";
                        bc.WriteToServer(dt);
                    }
                    con.Close();
                   
                }

            }
        }

i change my code into this.
but i got error "Invalid Cast Exception."
and i check SqlCeBulkCopy contain db null.
how can fix sqlcebulkcopy become have contain from my SQL CE?

**Comment by ErikEJ** [comment]
Please provide a full project and or your tables schema, then I will have a look!

**Comment by dsuryanto** [comment]
[Presetting.zip](https://github.com/ErikEJ/SqlCeBulkCopy/files/3922960/Presetting.zip)

![image](https://user-images.githubusercontent.com/50207764/70162691-a128f700-16f0-11ea-85c7-62723039449a.png)

**Comment by dsuryanto** [comment]
project and schema table already sent.
thank for help

**Comment by ErikEJ** [comment]
I do not want you full Windows Mobile solution, please provide a simple Windows console app that reproduces the issue.

**Comment by dsuryanto** [comment]
i will make it first.
sory for mistake give full windows mobile solution.

**Comment by dsuryanto** [comment]
[TestSqlCeLib_test.zip](https://github.com/ErikEJ/SqlCeBulkCopy/files/3926314/TestSqlCeLib_test.zip)

Dear Mr ErickEJ,
Here my simple application.
and i test it on Windows CE version 6.0

Cannot work when execute code
bc.WriteToServer(dt);

and got error "System.Data.SqlServerCe.SqlCeException was unhandled"
please help me and thank you.

**Comment by ErikEJ** [comment]
Hi, finally got around to have a look - I do not have VS 2008 or Windows CE. You need to create a desktop reproduction project, otherwise I cannot assist.

**Comment by dsuryanto** [comment]
needed for developing in vs2008 and windows CE.
can your DLL use in windows CE and vs 2008?

**Comment by ErikEJ** [comment]
Closing as the requested info/repro was never supplied.
