### ISSUE TITLE
SByte to TinyInt

### ISSUE THREAD

**Issue by veselac** [ErikEJ/SqlCeBulkCopy#14]
Hello, 
I encountered a problem saving values that are in TinyInt format. I read data from Mysql and use DataReader to write it via WriteToServer to SqlCe, in both databases there is a column of type TinyInt. Unfortunately, SqlCeBulkCopy works with TinyInt internally as SByte, so invoke error "Couldn't store (System.SByte) in column (status). The expected data type is TinyInt." The solution is to use a conversion similar to Convert.ToByte(dbReader.GetValue(i)) for the SByte type.

**Comment by ErikEJ** [comment]
Can you not do a CAST in your dataReader?

**Comment by veselac** [comment]
The column in the source and destination databases is TinyInt. So, I think it would be better to process it directly in the library. I have most queries in the format "SELECT * FROM xxx", which eliminates retyping directly in the query.

**Comment by ErikEJ** [comment]
Feel free to do a PR with a related test.
