### ISSUE TITLE
Analog for SQLite

### ISSUE THREAD

**Issue by davidrimshnick** [ErikEJ/SqlCeBulkCopy#15]
Hi, is there an analog of this library for SQLite for C#?

**Comment by ErikEJ** [comment]
Sadly no. There is no bulk API for Sqlite.

**Comment by davidrimshnick** [comment]
Bummer, thanks for the info.

**Comment by ErikEJ** [comment]
The best approach is to submit multiple INSERT statements in a single command  text.

**Comment by davidrimshnick** [comment]
Thanks, Microsoft seems to recommend multiple commands bundled into a
transaction.  Do you see an advantage one way or another?

https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/bulk-insert

**Comment by ErikEJ** [comment]
@davidrimshnick Yes, that would be the best approach

**Comment by davidrimshnick** [comment]
Thank you!
