### ISSUE TITLE
Ability to skip over duplicate records on copy

### ISSUE THREAD

**Issue by chameeya** [ErikEJ/SqlCeBulkCopy#7]
I have a case where I read in a CSV file and perform some slight processing on each record then insert into a table in database. These files contain 100,000+ records and presently take hours to process with our current package. I have made some optimisations by using the SqlCeResultSet but after 40,000 records the inserts slow down.

I plan to use SqlCeBulkCopy to speed this up by reading the data into a DataTable where I can perform the processing and then insert into the database.

But what can happen is the user during the processing can abort the software meaning some records have been inserted. In the present software it has exception handling when it encounters a duplicate record and moves on to the next row in the CSV.

Presently, before I can run SqlCeBulkCopy I must remove duplicates from my DataTable - or check before adding the new row.

Perhaps in SqlCeBulkCopy if it encounters a duplicate on the PK it can skip these via a option?

Have a think and let me know if you think this is a good idea.

**Comment by ErikEJ** [comment]
Provided you have enough memeory, removing the duplicates should be simple:

    DataTable distinctTable = dtEmp.DefaultView.ToTable( /*distinct*/ true);

But even if you use a Csv DataReader in order to save memory by reading the file one line at a time (for example http://www.lhotka.net/weblog/DataReaderForCSVFiles.aspx ) it could still be useful to be able to skip on duplicate primary key errors.. 

What do you think?

**Comment by chameeya** [comment]
Just to clarify, the duplicates would occur when contents of DataTable are inserted in database where some pre-existing records could exist left over from the previous aborted import. So I would take the input from CSV and check against the database (a simple exists check).

Overall I think it could be a useful option for some scenarios for BulkCopy to skip past PK errors.

so, Yes.

**Comment by ErikEJ** [comment]
How about simply dropping and recreating the target table if it contains aborted rows (of course you need some way to check this)

**Comment by ErikEJ** [comment]
OK, I will consider adding this option: IgnorePrimaryKeyViolationErrors 

Can you tell me the exact SqlException details you get for primary key violations? (Numbers etc)

**Comment by chameeya** [comment]
Apologies for delay - Holidays and firefighting

I have done a test run and the exception that I get is.
System.Data.SqlServerCe.SqlCeError
ErrorCode	-2147467259
Message	"A duplicate value cannot be inserted into a unique index. "
NativeError	25016

Hope that's enough.

**Comment by ErikEJ** [comment]
That is percfect, thanks!

**Comment by ErikEJ** [comment]
[ErikEJ.SqlCe40.zip](https://github.com/ErikEJ/SqlCeBulkCopy/files/998763/ErikEJ.SqlCe40.zip)
I have created a fix, but would like you to try it out before I add it to master - it has been attached here!

**Comment by ErikEJ** [comment]
Ping ?

**Comment by chameeya** [comment]
Apologies. I have not yet had a chance to try it as been v busy with other work. I am hopeful of getting a look early next week.

thank you for you patience.

**Comment by chameeya** [comment]
I was able to perform a test on it today and it works.
I tried a few scenarios and performed fine. Obviously when It is skipping the duplicates it slows down a lot but it is working correctly.

Thanks.
