### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Ismaelhm** [ErikEJ/SqlCeBulkCopy#9]
Hello, 

I'm trying your library but i can't good result, I receive one expceción but say "Succesfull" but when i go to see, i don't the bulk insertion.

I receive from SQL Express (datareader) then i convert to DAtatable, I see the rows, but nothing.

Thank you in advanced.
Ismael.

This is my source code:
                    cmd = New SqlCeCommand
                    cmd.Connection = sqlCeConn
                    cmd.CommandText = "SELECT * FROM " & tblArti & " WHERE art_Sincronizado='S'"
                    Dim sqlCeDR As SqlCeDataReader = cmd.ExecuteReader

                    '' === BULK COPY  START ==================================================================
                    ''/r: Imports ErikEJ.SqlCe

                    ''Dim dt As New DataTable()
                    ''dt.Load(sqlCeDR)
                    ''dt.TableName = tblArti

                    'rowsCount = 0
                    'Dim sqlCeConnection As String = "Data Source=" & g_path & dbName & ";Password='" & dbPassword & "'"
                    'Try
                    '    'SqlCeBulkCopyOptions.KeepIdentity + SqlCeBulkCopyOptions.KeepNulls
                    '    Using bc As SqlCeBulkCopy = New SqlCeBulkCopy(sqlCeConnection, SqlCeBulkCopyOptions.KeepIdentity + SqlCeBulkCopyOptions.KeepNulls)
                    '        bc.DestinationTableName = tblArti
                    '        bc.BatchSize = 10
                    '        bc.NotifyAfter = 20
                    '        'bc.BulkCopyTimeout = 10000
                    '        'bc.BatchSize = 4098

                    '        AddHandler bc.RowsCopied, AddressOf BulKCopy_Handler

                    '        'Dim mapName As New SqlCeBulkCopyColumnMapping()
                    '        'mapName.SourceColumn = ""
                    '        'mapName.DestinationColumn = ""
                    '        'bc.ColumnMappings.Add(mapName)
                    '        'bc.ColumnMappings.Add("autonro", "jau_autonro")
                    '        bc.ColumnMappings.Add("art_Codigo", "art_Codigo")
                    '        bc.ColumnMappings.Add("art_EAN_Articulo", "art_EAN_Articulo")
                    '        bc.ColumnMappings.Add("art_EAN_Caja", "art_EAN_Caja") ' Este es el campo nuevo de ellos.
                    '        bc.ColumnMappings.Add("art_Descripcion", "art_Descripcion")
                    '        bc.ColumnMappings.Add("art_Descripcion1", "art_Descripcion1")
                    '        bc.ColumnMappings.Add("art_Unidades_Caja", "art_Unidades_Caja")
                    '        bc.ColumnMappings.Add("art_Unidades_Palet", "art_Unidades_Palet")
                    '        bc.ColumnMappings.Add("art_Tipo_Vino", "art_Tipo_Vino")
                    '        bc.ColumnMappings.Add("art_Sincronizado", "art_Sincronizado")
                    '        bc.ColumnMappings.Add("art_Usuario", "art_Usuario")
                    '        bc.ColumnMappings.Add("art_TerminalSerie", "art_TerminalSerie")
                    '        bc.ColumnMappings.Add("art_Terminal", "art_Terminal")
                    '        bc.ColumnMappings.Add("art_fecha", "art_fecha")

                    '        bc.WriteToServer(sqlCeDR)
                    '    End Using
                    'Catch ex As SqlCeException
                    '    frmLogs.txtLogs.Text = ex.Message
                    'Catch ex As Exception
                    '    frmLogs.txtLogs.Text = ex.Message
                    'Finally

                    'End Try

                    'sqlCeDR.Close()
                    ''dt.Dispose()

                    '' Lo saco ahora para las pruebas
                    'Exit Sub
                    ' '' === BULK COPY  END ==================================================================

**Comment by Ismaelhm** [comment]
' = ART ============================================================================================
                frmLogs.txtLogs.Text = "Sincronización con Tabla de Articulos 1/3" & vbCrLf & frmLogs.txtLogs.Text

                ' Debo chequear que hay conexión Local
                If sqlCeConn Is Nothing Then conn()

                cmd = New SqlCeCommand
                cmd.Connection = sqlCeConn
                cmd.CommandText = "SELECT COUNT(*) FROM " & tblArti & " WHERE art_Sincronizado='N'"
                regs = cmd.ExecuteScalar
                If regs > 0 Then
                    frmLogs.MyProgressBar.Maximum = regs
                    frmLogs.MyProgressBar.Value = 0

                    cmd = New SqlCeCommand
                    cmd.Connection = sqlCeConn
                    cmd.CommandText = "SELECT * FROM " & tblArti & " WHERE art_Sincronizado='N'"
                    Dim sqlCeDR As SqlCeDataReader = cmd.ExecuteReader

                    ' === BULK COPY  START ==================================================================
                    '/r: Imports ErikEJ.SqlCe

                    Dim dt As New DataTable()
                    dt.Load(sqlCeDR)
                    dt.TableName = tblArti

                    rowsCount = 0
                    Dim sqlCeConnection As String = "Data Source=" & g_path & dbName & ";Password='" & dbPassword & "'"
                    Try
                        'SqlCeBulkCopyOptions.KeepIdentity + SqlCeBulkCopyOptions.KeepNulls
                        Using bc As SqlCeBulkCopy = New SqlCeBulkCopy(sqlCeConnection, SqlCeBulkCopyOptions.KeepIdentity + SqlCeBulkCopyOptions.KeepNulls)
                            bc.DestinationTableName = tblArti
                            bc.BatchSize = 10
                            bc.NotifyAfter = 20
                            'bc.BulkCopyTimeout = 10000
                            'bc.BatchSize = 4098

                            AddHandler bc.RowsCopied, AddressOf BulKCopy_Handler

                            'Dim mapName As New SqlCeBulkCopyColumnMapping()
                            'mapName.SourceColumn = ""
                            'mapName.DestinationColumn = ""
                            'bc.ColumnMappings.Add(mapName)
                            'bc.ColumnMappings.Add("autonro", "jau_autonro")
                            bc.ColumnMappings.Add("art_Codigo", "art_Codigo")
                            bc.ColumnMappings.Add("art_EAN_Articulo", "art_EAN_Articulo")
                            bc.ColumnMappings.Add("art_EAN_Caja", "art_EAN_Caja") ' Este es el campo nuevo de ellos.
                            bc.ColumnMappings.Add("art_Descripcion", "art_Descripcion")
                            bc.ColumnMappings.Add("art_Descripcion1", "art_Descripcion1")
                            bc.ColumnMappings.Add("art_Unidades_Caja", "art_Unidades_Caja")
                            bc.ColumnMappings.Add("art_Unidades_Palet", "art_Unidades_Palet")
                            bc.ColumnMappings.Add("art_Tipo_Vino", "art_Tipo_Vino")
                            bc.ColumnMappings.Add("art_Sincronizado", "art_Sincronizado")
                            bc.ColumnMappings.Add("art_Usuario", "art_Usuario")
                            bc.ColumnMappings.Add("art_TerminalSerie", "art_TerminalSerie")
                            bc.ColumnMappings.Add("art_Terminal", "art_Terminal")
                            bc.ColumnMappings.Add("art_fecha", "art_fecha")

                            bc.WriteToServer(dt)
                        End Using
                    Catch ex As SqlCeException
                        frmLogs.txtLogs.Text = ex.Message
                    Catch ex As Exception
                        frmLogs.txtLogs.Text = ex.Message
                    Finally

                    End Try

                    sqlCeDR.Close()
                    dt.Dispose()
                    '' === BULK COPY  END ==================================================================

**Comment by ErikEJ** [comment]
What is the exception??

**Comment by ErikEJ** [comment]
Are you checking the correct database file?

Pls share your connection string

**Comment by Ismaelhm** [comment]
Hello Erik,

I tried to change some columns (source) name and the connector say me that there isn't column with this name, but i sent the connector and  the structura of table.


Dim sqlCeConnection As String = "Data Source=" & g_path & dbName & ";Password='" & dbPassword & "'"
where 
Public g_path As String = "\Flash\RFID HF Jaulones"
and 
Public Const dbName As String = "\Rfid_HF_Jaulones.sdf"  

TAble Structure. I creatd by command.
            cmd = New SqlCeCommand
            cmd.Connection = sqlCeConn
            '"jau_autonro bigint IDENTITY(1,1) PRIMARY KEY NOT NULL," & _
            cmd.CommandText = "CREATE TABLE " & tblJau & "(" & _
                                "jau_Codigo nvarchar(30) PRIMARY KEY NOT NULL," & _
                                "jau_Matricula nvarchar(50)," & _
                                "jau_Lote nvarchar(25)," & _
                                "jau_Fecha_Llenado datetime," & _
                                "jau_Sincronizado nvarchar(1) DEFAULT 'S'," & _
                                "jau_Usuario nvarchar(12)," & _
                                "jau_Terminal nvarchar(12)," & _
                                "jau_TerminalSerie nvarchar(25)," & _
                                "jau_fecha datetime" & _
                                ")"
            cmd.ExecuteNonQuery()

Thanks for your time.
Ismael.

**Comment by ErikEJ** [comment]
In order to help with this, I need a repro project, feel free to re-open when you can provide that

**Comment by Ismaelhm** [comment]
I could sent you the module with the code, is it valid for your?

BEst regards.
Ismael.

**Comment by ErikEJ** [comment]
Yes, please

**Comment by Ismaelhm** [comment]
I just to sent the module by mail.

Best Regards.
Ismael.
